### PR TITLE
[WIP] micronaut data txn management

### PR DESCRIPTION
**Pull request by drmaas**
Haven't added jooq code yet - unsure how to map the exceptions into micronaut data types.

Also unsure how to test this.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for starting the work, will take a look

**Comment by graemerocher** [comment]
A JOOQ PR is now present https://github.com/micronaut-projects/micronaut-sql/pull/124

We will release 1.0.1 this week and then can merge both these PRs

**Comment by graemerocher** [comment]
@drmaas The JOOQ PR uses a custom gradle configuration for the tests https://github.com/micronaut-projects/micronaut-sql/pull/124/files#diff-2765d8030523e314d93a81403128719bR45

Would this be a viable approach for this PR?

**Comment by graemerocher** [comment]
Micronaut Data 1.0.1 has been released

**Comment by graemerocher** [comment]
Manually applied. Thanks https://github.com/micronaut-projects/micronaut-sql/commit/fb6b6928b67f630a6352a6bcaf49066081031349

**Comment by drmaas** [comment]
Thanks @graemerocher - have been busy lately and didn't have a chance to circle back on this.

**Pull request closed without merging**
