### PR TITLE
build: use mysql-connector-j dependency

### PR DESCRIPTION
**Pull request by sdelamo**
see: https://github.com/micronaut-projects/micronaut-starter/pull/2064

### CODE REVIEW

**Comment by wetted** [comment]
This needs a release of `micronaut-test-resources` with https://github.com/micronaut-projects/micronaut-test-resources/pull/409

**Comment by radovanradic** [comment]
> This needs a release of `micronaut-test-resources` with [micronaut-projects/micronaut-test-resources#409](https://github.com/micronaut-projects/micronaut-test-resources/pull/409)

And new gradle plugin with the new test resources version

**Comment by radovanradic** [comment]
> > This needs a release of `micronaut-test-resources` with [micronaut-projects/micronaut-test-resources#409](https://github.com/micronaut-projects/micronaut-test-resources/pull/409)
> 
> And new gradle plugin with the new test resources version

New gradle plugin 4.1.2 and test resources 2.1.0 should resolve this issue.

**Comment by wetted** [comment]
ping @sdelamo 

I think this should be good to go https://github.com/micronaut-projects/micronaut-starter/pull/2064 depends on it.

**Review by radovanradic — APPROVED** [review]

**Pull request merged**
