### PR TITLE
jasync health check failing

### PR DESCRIPTION
**Pull request by arudge**
We started using jasync in our project and the default health check always results in a timeout.
We had to implement our own. 
I think there is an issue with the ` s.onNext(status.build());` being subscribed on. 
I wrote a failing test using the `EmbeddedServer` against the existing code.
I then modified the existing health check to pass that failing test.

I'd like to clean this all up with a :bowtie:,  but I wanted to get some feedback on using the `EmbeddedServer` for testing in this project and the overall approach.

### CODE REVIEW

**Comment by graemerocher** [comment]
All looks fine to me, any others changes you want to make?

**Comment by arudge** [comment]
Great, Yes I'd like to clean things up a bit. 
I'll do that now. Thanks for the preliminary review.

**Comment by graemerocher** [comment]
Will need to rebase as well. Thanks

**Comment by mliberato** [comment]
I've tested on my application and it has resolved the problem here.

Will this fix arrive at 1.3.x or 1.4.x releases? Without it basically nobody can use default health endpoint unless @Replaces jasync health check bean.

@arudge it would be great to fix the typo in the class name as well. From `JaysncHealthIndicator` to `JasyncHealthIndicator`

**Comment by arudge** [comment]
I'll dust this off....

**Comment by arudge** [comment]
@graemerocher this is ready to go now

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
