### PR TITLE
JOOQ integration for micronaut-data-tx

### PR DESCRIPTION
**Pull request by lightoze**
Waiting for micronaut-data 1.0.1 to finalize PR.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks I am working towards a 1.0.1 this week

**Comment by graemerocher** [comment]
Micronaut Data 1.0.1 has been released

**Comment by lightoze** [comment]
@graemerocher I updated the PR to be ready for 2.0.0.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
