### PR TITLE
Disable JPA via configuration

### PR DESCRIPTION
**Pull request by sdelamo**
This would be ease for example project generation in starter. Right now we generate an application without any entity. Thus the application tests will fail until the user creates a `@Entity` and defines `jpa.default.entity-scan.packages`

### CODE REVIEW

**Comment by sdelamo** [comment]
failure Gradle scan https://ge.micronaut.io/s/in4pzerinyyl2

**Comment by graemerocher** [comment]
@sdelamo please rebase

**Comment by sdelamo** [comment]
> @sdelamo please rebase

done

**Comment by graemerocher** [comment]
The name of the configuration option is not very consistent with the existing no (it uses `micronaut.hibernate.jpa` instead of just `jpa`) and also doesn't allow disabling individual JPA configurations.

WDYT @dstepanov ?

**Comment by dstepanov** [comment]
Would it be better to create a simple entity in the starter?

**Comment by sdelamo** [comment]
@dstepanov can we merge this?

**Comment by graemerocher** [comment]
my comment was never addressed, why the inconsistent name?

**Review by graemerocher — APPROVED** [review]

**Review by dstepanov — APPROVED** [review]

**Pull request merged**
