### PR TITLE
Add ability to configure jOOQ ConverterProvider 

### PR DESCRIPTION
**Pull request by morki**
and create default implementation using builtin Jackson for JSON and JSONB types (must me configured)

https://www.jooq.org/doc/3.14/manual/sql-execution/fetching/converter-provider/

### CODE REVIEW

**Comment by morki** [comment]
It is related to new feature in jOOQ 3.14 - transforming database JSON values, by default jOOQ use reflection and creates default ObjectMapper if Jackson is on classpath. But of course this default ObjectMapper is not configured by Micronaut, so is not using introspection and configured modules (like KotlinModule in our case).

So this PR adds:
- missing ability to replace ConverterProvider (needed anyway)
- default implementation configurable by application configuration to create Converter with built-in ObjectMapper configured by Micronaut

**Comment by graemerocher** [comment]
Does this help with the native image problems?

**Comment by morki** [comment]
I some way, it does not resolve https://github.com/micronaut-graal-tests/micronaut-jooq-graal/issues/9 but It uses `Introspection` for serialization and deserialization, so no additional reflection configuration is needed.

**Comment by morki** [comment]
@graemerocher is this something that can be accepted or do I have to split those functionalities to:

1. add option to configure ConverterProvider (really needed)
2. default implementation using built-in ObjectMapper (can be done on user side)

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
