### PR TITLE
ci: GraalVM Matrix

### PR DESCRIPTION
**Pull request by micronaut-build**
Update common files

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
@timyates can you check the failure?

**Comment by timyates** [comment]
@sdelamo I think this is caused by https://github.com/micronaut-projects/micronaut-project-template/pull/248 Denis has reported it in gitter

**Comment by sdelamo** [comment]
I removed it https://github.com/micronaut-projects/micronaut-sql/pull/690/commits/d6d79c5d793c0e077b0048a3586d8738109ef777 and still failed

**Comment by timyates** [comment]
Think it failed on something else...  Rerunning to see if it's flaky

**Comment by timyates** [comment]
Still failing...  Investigating

**Comment by timyates** [comment]
Got it failing locally...  Trying to work out why...

**Comment by timyates** [comment]
It's a classnotfound somewhere in graal 😿 

https://ge.micronaut.io/s/u55fv35dpyaog/console-log#L176

**Comment by timyates** [comment]
@graemerocher any ideas on how to debug this?

**Comment by timyates** [comment]
💚

**Pull request merged**
