### PR TITLE
use collect for thread safe access

### PR DESCRIPTION
**Pull request by rawilder**

### CODE REVIEW

**Comment by rawilder** [comment]
I was noodling on this a bit. The synchronizedSet is the least code change but there's also a solution in which we leave entities untouched and instead use `addAll` with `.collect(Collectors.toSet())` instead of `.forEach(entities::add)`. Any thoughts on that?

**Comment by graemerocher** [comment]
`.collect(Collectors.toSet())` would be better

**Comment by rawilder** [comment]
@graemerocher looks like the gradle download of one of the resources is experiencing a 403. I was seeing this locally as well.

**Comment by rawilder** [comment]
Any update with regards to the build error?

```
Could not GET 'dl.bintray.com/micronaut/core-releases-local/io/micronaut/build/micronaut-gradle-plugins/2.0.11/micronaut-gradle-plugins-2.0.11.pom'. Received status code 403 from server: Forbidden
```

**Comment by rawilder** [comment]
@graemerocher any updates?

**Comment by graemerocher** [comment]
looks like build plugins need updating: https://github.com/micronaut-projects/micronaut-sql/blob/master/build.gradle#L7

@melix could you assist in getting this build up-to-date?

**Comment by melix** [comment]
I will take a look.

**Comment by graemerocher** [comment]
Replaced by https://github.com/micronaut-projects/micronaut-sql/pull/524

**Pull request closed without merging**
